import { type NextPage } from "next";
import Head from "next/head";
import { FormGroup } from "~/components/FormGroup";
import { Input } from "~/components/Input";
import { useState } from "react";
import { api } from "~/utils/api";
import { Button } from "~/components/Button";
import Image from "next/image";

const GeneratePage: NextPage = () => {
  const [form, setForm] = useState({
    prompt: "",
    color: "",
    style: "",
  });
  const [image, setImage] = useState("");

  const generateIcon = api.generate.generateIcon.useMutation({
    onSuccess(data) {
      if (!data.s3ImageUrl) return;
      setImage(data.s3ImageUrl);
    },
  });

  function handleFormSubmit(e: React.FormEvent) {
    e.preventDefault();
    generateIcon.mutate({
      prompt: form.prompt,
      color: form.color,
      style: form.style,
    });
  }

  function updateForm(key: string) {
    return function (e: React.ChangeEvent<HTMLInputElement>) {
      setForm((prev) => ({ ...prev, [key]: e.target.value }));
    };
  }

  return (
    <>
      <Head>
        <title>Generate Icons</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="container mx-auto flex flex-col gap-4 px-8 py-12">
        <h1 className="text-6xl">Generate your icons</h1>
        <p>Fill out the form below to start generating your icons.</p>
        <form className="flex flex-col gap-4" onSubmit={handleFormSubmit}>
          <h2 className="text-2xl">
            Describe what you want your icon to look like
          </h2>
          <FormGroup>
            <label>Prompt</label>
            <Input value={form.prompt} onChange={updateForm("prompt")} />
          </FormGroup>
          <h2 className="text-2xl">Pick your icon color</h2>
          <FormGroup>
            <label>
              <Input value={form.color} onChange={updateForm("color")} />
            </label>
          </FormGroup>
          <h2 className="text-2xl">Pick your icon style</h2>
          <FormGroup>
            <label>
              <Input value={form.style} onChange={updateForm("style")} />
            </label>
          </FormGroup>

          <Button
            isLoading={generateIcon.isLoading}
            disabled={generateIcon.isLoading}
          >
            Submit
          </Button>
        </form>
        {!!image && (
          <>
            <h2 className="text-2xl">Your icons</h2>
            <section className="grid grid-cols-4 gap-4">
              <Image
                src={image}
                alt="an image of your generated prompt"
                width={100}
                height={100}
                className="w-full"
              />
            </section>
          </>
        )}
      </main>
    </>
  );
};

export default GeneratePage;
