import { ExampleComponent } from "@components/example-component";
import { NavBar } from "@components/nav-bar";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <ExampleComponent />
      </main>
    </>
  );
}
